fix example1.js module path
I have problem to execute the example1.js.

[~/src/node-sapnwrfc] ➔ LD_LIBRARY_PATH=nwrfcsdk/lib/ node examples/example1.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'sapnwrfc'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/agebert/src/node-sapnwrfc/examples/example1.js:4:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)